project 'RxSwiftExample.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExample
  pod 'Moya'
  pod 'SwifterSwift'            # All Extensions
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  
end
